# Default values for hellomsa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

services:
  frontendapp:
    name: frontendapp
    image: "bamyam/frontendapp" # Replace with your actual image name
    tag: v1
    port: 3000

  productapp:
    name: productapp  
    image: "bamyam/productapp" # Replace with your actual image name
    tag: v1
    port: 8000

  userapp:
    name: userapp  
    image: "bamyam/userapp" # Replace with your actual image name
    tag: v1
    port: 8010

nginx:
  image: nginx
  tag: latest
